### ISSUE TITLE
Reproducing results?

### ISSUE THREAD

**Issue by junxiant** [Bardhitoo/lung_cancer_proj#1]
Hello, great work on this project, are there any instructions on how to reproduce the results, or what each script does?

**Comment by Bardhitoo** [comment]
Hello @junxiant ! I'm already on the process of documenting the whole process. The new update should be coming this week. Thanks for your patience

**Comment by Bardhitoo** [comment]
@junxiant  This should help you get going for reproducing the results. Please let me know if you run into issues
